version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - /data/postgres:/data/postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  api:
    build: ./
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - mongo
      - postgres
